apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver  # The name that this container will have.
    image: nginx:1.14.0 # The image on which it is based.
  hostNetwork: true
  schedulerName: "StupidScheduler"